timezone: "Asia/Kolkata"
attendance:
  url: "https://your.attendance.portal"
hotkeys:
  open_attendance: "ctrl+a"
  start_recording: "ctrl+alt+r"
  stop_recording: "ctrl+alt+s"
obs:
  websocket_host: "localhost"
  websocket_port: 4455
  websocket_password: "mypassword123"
teams:
  meetings:
    - title: "Stream Training"
      url: "ur meeting link"
      start_time: "08:30"
      duration_min: 540
      days: ["mon","tue","wed","thu","fri"]
